insert into public.tags (slug, label, kind, category, constraints)
values
  ('size-class:small', 'Small', 'factual', 'size-class', '{}'::jsonb),
  ('size-class:medium', 'Medium', 'factual', 'size-class', '{}'::jsonb),
  ('size-class:large', 'Large', 'factual', 'size-class', '{}'::jsonb),
  ('win:classic', 'Classic', 'factual', 'win-condition', '{}'::jsonb),
  ('win:city-hold', 'City Hold', 'factual', 'win-condition', '{}'::jsonb),
  ('win:tournament', 'Tournament', 'factual', 'win-condition', '{}'::jsonb),
  ('win:other', 'Other win', 'factual', 'win-condition', '{}'::jsonb),
  ('roads:on', 'Roads on', 'factual', 'roads', '{}'::jsonb),
  ('roads:off', 'Roads off', 'factual', 'roads', '{}'::jsonb),
  ('portals:on', 'Portals on', 'factual', 'portals', '{}'::jsonb),
  ('portals:off', 'Portals off', 'factual', 'portals', '{}'::jsonb),
  ('topology:ring', 'Ring', 'factual', 'topology', '{}'::jsonb),
  ('topology:chain', 'Chain', 'factual', 'topology', '{}'::jsonb),
  ('topology:hub', 'Hub', 'factual', 'topology', '{}'::jsonb),
  ('topology:shared-web', 'Shared web', 'factual', 'topology', '{}'::jsonb),
  ('topology:balanced', 'Balanced', 'factual', 'topology', '{}'::jsonb),
  ('topology:random', 'Random', 'factual', 'topology', '{}'::jsonb),
  ('neutral:low', 'Low neutrals', 'factual', 'neutral', '{}'::jsonb),
  ('neutral:medium', 'Medium neutrals', 'factual', 'neutral', '{}'::jsonb),
  ('neutral:high', 'High neutrals', 'factual', 'neutral', '{}'::jsonb),
  ('neutral-castles:on', 'Neutral castles', 'factual', 'neutral', '{}'::jsonb),
  ('experimental-size', 'Experimental size', 'factual', 'risk', '{}'::jsonb),
  ('high-zone-density', 'High zone density', 'factual', 'risk', '{}'::jsonb),
  ('many-castles', 'Many castles', 'factual', 'risk', '{}'::jsonb),
  ('competitive', 'Competitive', 'descriptive', 'audience', '{"minPlayerCount": 2, "winConditionKinds": ["classic"], "exclusiveWith": ["casual"]}'::jsonb),
  ('casual', 'Casual', 'descriptive', 'audience', '{"exclusiveWith": ["competitive"]}'::jsonb),
  ('macro', 'Macro', 'descriptive', 'pacing', '{}'::jsonb),
  ('tempo', 'Tempo', 'descriptive', 'pacing', '{}'::jsonb),
  ('high-resource', 'High resource', 'descriptive', 'economy', '{"exclusiveWith": ["low-resource"]}'::jsonb),
  ('low-resource', 'Low resource', 'descriptive', 'economy', '{"exclusiveWith": ["high-resource"]}'::jsonb),
  ('chokepoints', 'Chokepoints', 'descriptive', 'layout', '{}'::jsonb),
  ('wide', 'Wide', 'descriptive', 'layout', '{}'::jsonb),
  ('beginner-friendly', 'Beginner friendly', 'descriptive', 'audience', '{}'::jsonb),
  ('high-risk', 'High risk', 'descriptive', 'layout', '{}'::jsonb),
  ('exploration-heavy', 'Exploration heavy', 'descriptive', 'pacing', '{}'::jsonb)
on conflict (slug) do update
set
  label = excluded.label,
  kind = excluded.kind,
  category = excluded.category,
  constraints = excluded.constraints;
